# JetBrains Mono

```{r, include=FALSE}
source("_common.R")
```

```{r}
htmltools::tagList(
  btn_link("https://fonts.google.com/specimen/JetBrains+Mono", "Google Fonts"),
  btn_link("https://github.com/JetBrains/JetBrainsMono", "GitHub")
)
```

## Specimen

### R

```r
```{r, echo=FALSE, results="asis"}
xfun::file_string("assets/samples/sample.R")
```
```

### Python

```python
```{r, echo=FALSE, results="asis"}
xfun::file_string("assets/samples/sample.py")
```
```

### C

```c
```{r, echo=FALSE, results="asis"}
xfun::file_string("assets/samples/sample.c")
```
```

### JavaScript

```javascript
```{r, echo=FALSE, results="asis"}
xfun::file_string("assets/samples/sample.js")
```
```

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono&display=swap" rel="stylesheet">

```{css}
.sourceCode { font-family: "JetBrains Mono", monospace; }
```

```{r}
htmltools::includeScript("assets/samples/editable-code.js")
```
