# Libre Caslon Display

```{r, include=FALSE}
source("_common.R")
```

```{r}
htmltools::tagList(
  btn_link("https://fonts.google.com/specimen/Libre+Caslon+Display", "Google Fonts"),
  btn_link("https://github.com/impallari/Libre-Caslon-Display", "GitHub")
)
```

## Specimen

::: {.callout}

:::: {.disp-1}
Modernize Title Display Technologies
::::

:::: {.disp-2}
Modernize Title Display Technologies
::::

:::: {.disp-3}
Modernize Title Display Technologies
::::

:::: {.disp-4}
Modernize Title Display Technologies
::::

:::: {.disp-5}
Modernize Title Display Technologies
::::

:::

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Libre+Caslon+Display&display=swap" rel="stylesheet">

```{css}
.callout { font-family: "Libre Caslon Display", serif; }
.callout .disp-1 { font-size: 2.5rem; }
.callout .disp-2 { font-size: 2rem; }
.callout .disp-3 { font-size: 1.5rem; }
.callout .disp-4 { font-size: 1.2rem; }
.callout .disp-5 { font-size: 1rem; }
```
