# Red Hat Display

## Specimen

::: {.rmdnote}

:::: {.disp-1}
Modernize Title Display Technologies
::::

:::: {.disp-2}
Modernize Title Display Technologies
::::

:::: {.disp-3}
Modernize Title Display Technologies
::::

:::: {.disp-4}
Modernize Title Display Technologies
::::

:::: {.disp-5}
Modernize Title Display Technologies
::::

:::: {.disp-1}
_Modernize Title Display Technologies_
::::

:::: {.disp-2}
_Modernize Title Display Technologies_
::::

:::: {.disp-3}
_Modernize Title Display Technologies_
::::

:::: {.disp-4}
_Modernize Title Display Technologies_
::::

:::: {.disp-5}
_Modernize Title Display Technologies_
::::

:::: {.disp-bold-1}
Modernize Title Display Technologies
::::

:::: {.disp-bold-2}
Modernize Title Display Technologies
::::

:::: {.disp-bold-3}
Modernize Title Display Technologies
::::

:::: {.disp-bold-4}
Modernize Title Display Technologies
::::

:::: {.disp-bold-5}
Modernize Title Display Technologies
::::

:::: {.disp-bold-1}
_Modernize Title Display Technologies_
::::

:::: {.disp-bold-2}
_Modernize Title Display Technologies_
::::

:::: {.disp-bold-3}
_Modernize Title Display Technologies_
::::

:::: {.disp-bold-4}
_Modernize Title Display Technologies_
::::

:::: {.disp-bold-5}
_Modernize Title Display Technologies_
::::

:::

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Red+Hat+Display:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">

```{css}
.rmdnote { font-family: "Red Hat Display", serif; }
.rmdnote .disp-1 { font-size: 2.5rem; }
.rmdnote .disp-2 { font-size: 2rem; }
.rmdnote .disp-3 { font-size: 1.5rem; }
.rmdnote .disp-4 { font-size: 1.2rem; }
.rmdnote .disp-5 { font-size: 1rem; }
.rmdnote .disp-bold-1 { font-size: 2.375rem; font-weight: 700; }
.rmdnote .disp-bold-2 { font-size: 2rem; font-weight: 700; }
.rmdnote .disp-bold-3 { font-size: 1.5rem; font-weight: 700; }
.rmdnote .disp-bold-4 { font-size: 1.2rem; font-weight: 700; }
.rmdnote .disp-bold-5 { font-size: 1rem; font-weight: 700; }
```
