# Source Code Pro

```{r, include=FALSE}
options(width = 60)

knitr::opts_chunk$set(
  comment = "#>",
  collapse = TRUE,
  echo = FALSE
)
```

<a href="https://fonts.google.com/specimen/Source+Code+Pro" class="btn btn-outline-secondary" role="button" target="_blank">
<i class="bi bi-box-arrow-up-right"></i>
Google Fonts
</a>
<a href="https://github.com/adobe-fonts/source-code-pro" class="btn btn-outline-secondary" role="button" target="_blank">
<i class="bi bi-box-arrow-up-right"></i>
GitHub
</a>

## Specimen

### R

```r
```{r, echo=FALSE, results="asis"}
xfun::file_string("assets/samples/sample.R")
```
```

### Python

```python
```{r, echo=FALSE, results="asis"}
xfun::file_string("assets/samples/sample.py")
```
```

### C

```c
```{r, echo=FALSE, results="asis"}
xfun::file_string("assets/samples/sample.c")
```
```

### JavaScript

```javascript
```{r, echo=FALSE, results="asis"}
xfun::file_string("assets/samples/sample.js")
```
```

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Source+Code+Pro:ital,wght@0,400;0,700;1,400&display=swap" rel="stylesheet">

```{css}
.sourceCode { font-family: "Source Code Pro", monospace; }
```
