# Source Serif

```{r, include=FALSE}
options(width = 60)

knitr::opts_chunk$set(
  comment = "#>",
  collapse = TRUE,
  echo = FALSE
)
```

<a href="https://fonts.google.com/specimen/Source+Serif+Pro" class="btn btn-outline-secondary" role="button" target="_blank">
<i class="bi bi-box-arrow-up-right"></i>
Google Fonts (Source Serif Pro)
</a>
<a href="https://fonts.google.com/specimen/Source+Serif+4" class="btn btn-outline-secondary" role="button" target="_blank">
<i class="bi bi-box-arrow-up-right"></i>
Google Fonts (Source Serif 4)
</a>
<a href="https://github.com/adobe-fonts/source-serif" class="btn btn-outline-secondary" role="button" target="_blank">
<i class="bi bi-box-arrow-up-right"></i>
GitHub
</a>

## Specimen

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Source+Serif+Pro:ital,wght@0,400;0,700;1,400&display=swap" rel="stylesheet">

```{css}
.live { font-family: "Source Serif Pro", sans-serif; }
```

```{r}
htmltools::includeCSS("assets/ctxedit/ctxedit.css")
htmltools::includeHTML("assets/ctxedit/sample.html")
htmltools::includeHTML("assets/ctxedit/ctxedit-ui.html")
htmltools::includeHTML("assets/ctxedit/ctxedit-js.html")
```
